name: Generate HTML

on:
  push:
    branches:
      - main  # Adjust to your default branch
    paths:
      - 'text.md'

jobs:
  generate_html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 markdown

    - name: Run Python Script
      run: python format_html.py

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add index.html
        git commit -m "Generate index.html from new text.md"
        git push
